package model

type Order struct {
	OrderId string `json:"orderId"`
	Amount  int    `json:"amount"`
}

type Event struct {
	ID        string                // generated by service
	EventId   string                // generated by service
	Type      string                 // e.g. "order.created"
	Source    string                 // "web", "mobile", "system"
	Timestamp int64                  // unix seconds
	Payload   map[string]interface{} // business-specific data
}
